name: Build and Package Node.js Application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pkg

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Install pkg
        run: npm i -g pkg

      - name: Build Executable
        run: pkg . --out-path build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Executable
          path: ./build/*
